---
title: "CorrelAid X Challenge: Import and Clean Unfallatlas Data"
author: "LC Berlin"
date: "`r Sys.Date()`"    ## current date
output:
  html_document:
    theme: paper          ## choose theme
    highlight: kate       ## choose coding style
    toc_depth: 2          ## table of content
    toc_float: true       ## allow toc next to doc#
    code_folding: show    ## include + show code
    #code_folding: hide    ## include code but hide it
    code_download: true   ## allow download of source
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE, warning = FALSE, 
  fig.showtext = TRUE, fig.retina = 1,
  fig.width = 10, fig.height = 7.5
)
```

```{r r-prep, message=FALSE}
library(tidyverse)
#library(readr)
library(here)
library(glue)
library(colorspace)
library(ragg)

theme_set(theme_minimal(base_size = 15, base_family = "Oswald"))

theme_update(legend.position = "top")
```

[Data from Unfallatlas](https://unfallatlas.statistikportal.de/_opendata2020.html) comes as either tables (`.txt`) or shapefiles (`.shp`) 
for the years 2016 to 2019 for all Germany except Mecklenburg-Vorpommern (at least what we expect from the [interactive web map](https://unfallatlas.statistikportal.de/))


## IMPORT DATA

```{r}
## links to .csv .zip files
links <- c(
  "https://www.opengeodata.nrw.de/produkte/transport_verkehr/unfallatlas/Unfallorte2016_EPSG25832_CSV.zip",
  "https://www.opengeodata.nrw.de/produkte/transport_verkehr/unfallatlas/Unfallorte2017_EPSG25832_CSV.zip",
  "https://www.opengeodata.nrw.de/produkte/transport_verkehr/unfallatlas/Unfallorte2018_EPSG25832_CSV.zip",
  "https://unfallatlas.statistikportal.de/app/UnfalldatenDownload/Unfallorte2019_LinRef_csv.zip"
)

## .txt files of interest within each zip folder
files <- c(
  "csv/Unfallorte_2016_LinRef.txt",
  "csv/Unfallorte2017_LinRef.txt",
  "csv/Unfallorte2018_LinRef.txt",
  "csv/Unfallorte2019_LinRef.txt"
)

## function to download .zip to temp dir, extract + import data
read_multiple_zips <- function(link, file) {
    temp <- tempfile()
    download.file(link, temp)
    dat <- read_csv2(unz(temp, file))
    unlink(temp)
    dat
}

## process all 4 files + combine them in one df
df <- 
  map2_dfr(
    .x = links, 
    .y = files,
    .f = read_multiple_zips
  ) %>% 
  mutate_at(c(1, 8, 9), as.numeric) %>% 
  mutate(
    OBJECTID = if_else(is.na(OBJECTID), OBJECTID_1, OBJECTID),
    ULICHTVERH = if_else(is.na(ULICHTVERH), LICHT, ULICHTVERH),
    IstSonstige = if_else(is.na(IstSonstige), IstSonstig, IstSonstige)
  ) %>% 
  dplyr::select(-FID, -OBJECTID_1, -LICHT, -IstSonstig, -IstStrasse)
```

For the years 2016 to 2019, there are {nrow(df)} observations of all types of accidents with persons being injured ("Unfall mit Personenschaden").

## TRANSLATION

```{r}
## trnslation of column headers
## metadata: https://www.opengeodata.nrw.de/produkte/transport_verkehr/unfallatlas/DSB_Unfallatlas.pdf

df_eng <- 
  df %>% 
  rename(
    id = OBJECTID, 
    id_unknown = UIDENTSTLA, 
    federal_state = ULAND, 
    admin_district = UREGBEZ, 
    district = UKREIS, 
    municipality = UGEMEINDE, 
    year = UJAHR, 
    month = UMONAT, 
    hour = USTUNDE, 
    wday = UWOCHENTAG, ## 1: Sun; 2: Mon; ...
    category = UKATEGORIE, ## 1: dead; 2: serious injuries; 3: light injuries
    manner = UART, ## see metadata
    type = UTYP1,  ## see metadata
    is_bike = IstRad, 
    is_car = IstPKW, 
    is_pedestrian = IstFuss, 
    is_mtrcycle = IstKrad, 
    is_freightvehicle = IstGkfz,
    is_other = IstSonstige, 
    light_condition = ULICHTVERH, ## 0: day; 1: dawn/dusk; 2: dark
    street_condition = STRZUSTAND,  ## 0: dry; 1: wet; 2: icy
    x_lin = LINREFX, 
    y_lin = LINREFY, 
    x_wgs = XGCSWGS84, 
    y_wgs = YGCSWGS84
  ) %>% 
  dplyr::select(id:is_freightvehicle, is_other, street_condition, x_lin:y_wgs)

rds <- here("data", "unfallatlas_eng.Rds")
if(!file.exists(rds)) { write_rds(df_eng, rds)}
```


## BERLIN BIKE ACCIDENT DATA

```{r}
## Berlin and bike accidents only
df_bln_bikes <-
  df_eng %>% 
  filter(
    federal_state == "11",  ## Berlin only (13,390)
    is_bike == 1  ## Accidents involving bikes only (5,005)
  )

rds <- here("data", "unfallatlas_eng_berlin_bikes.Rds")
if(!file.exists(rds)) { write_rds(df_bln_bikes, rds)}
```


## DATA EXPLORATION

```{r}
df_bln_bikes %>% 
  group_by(year) %>% 
  count()
```

