---
title: "CorrelAid X Challenge: Get Accident Data for Major Cities in Germany via datenguidepy"
author: "Cédric Scherer"
date: "`r Sys.Date()`"    ## current date
output:
  html_document:
    theme: paper          ## choose theme
    highlight: kate       ## choose coding style
    toc_depth: 2          ## table of content
    toc_float: true       ## allow toc next to doc#
    code_folding: show    ## include + show code
    #code_folding: hide    ## include code but hide it
    code_download: true   ## allow download of source
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE, warning = FALSE,
  fig.showtext = TRUE, fig.retina = 1,
  fig.width = 10, fig.height = 7.5
)
```

```{r r-prep, message=FALSE}
library(tidyverse)
library(reticulate)
library(DT)

#py_install("matplotlib")
#py_install("datenguidepy", pip = T)
```

```{python py-prep}
import os
if not os.path.basename(os.getcwd()) == "datenguide-python":
    os.chdir("..")
    
    
from datenguidepy.query_helper import get_regions, get_statistics, get_availability_summary
from datenguidepy import Query
import pandas as pd
import matplotlib.pyplot as plt
```

```{python info-stats}
r = get_regions().query("level == 'nuts3'")
print(r[(r['name']=='Berlin')])

print(r[r['name'].str.contains("Berlin|Hamburg|München|Köln|Frankfurt|Stuttgart|Düsseldorf|Dortmund|Essen|Leipzig|Bremen|Dresden")])

stats_names = get_statistics()

# Availability
availability = get_availability_summary()
print(availability.shape)
```

## Browse Statistics

```{r table-short, include = F}
py$stats_names %>%
  select(-long_description) %>% 
  rownames_to_column %>% 
  datatable(
    rownames = F,
    colnames = c("Statistik", "Kurzbeschreibung"),
    class = 'cell-border stripe',
    filter = 'top',
    extensions = 'Buttons',
    #options = list(
    #  dom = 'Bfrtip',
    #  buttons = c('copy', 'csv', 'pdf')
    #)
  )
```

```{r table-details}
py$stats_names %>%
  rownames_to_column %>% 
  datatable(
    rownames = F,
    colnames = c("Statistik", "Kurzbeschreibung", "Beschreibung"),
    class = 'cell-border stripe',
    filter = 'top',
    extensions = 'Buttons',
    #options = list(
    #  dom = 'Bfrtip',
    #  buttons = c('copy', 'csv', 'pdf')
    #)
  )
```

## Query Statistics Accidents + some info on cities (pop, dens, cars)

```{python stats-migration}
q = Query.region(['11000', '14612', '14713', '02000', '04011', '05111', '05113', '05315', '05913', '06412', '08111', '09162'])

#stat = q.add_field("VER056")
#stat.get_info()

q.add_field('BEV016')  ## Einwohner
q.add_field('AI0201')  ## Bevölkerungsdichte (Einwohner je qkm)
q.add_field('AI0113')	 ## Siedlungs- und Verkehrsfläche je Einwohner
q.add_field('AI1301')  ## Pkw je 1.000 Einwohner
q.add_field('AI1302')  ## Straßenverkehrsunfälle je 10.000 Einwohner
q.add_field('AI1303')  ## Straßenverkehrsunfälle je 10.000 Kfz
q.add_field('AI1304')  ## Getötete bei Straßenverkehrsunfällen je 100.000 EW
q.add_field('AI1305')  ## Verletzte bei Straßenverkehrsunfällen je 100.000EW
q.add_field('VER001')  ## Unfälle (insgesamt)
q.add_field('VER002')  ## Unfälle mit Personenschaden
q.add_field('VER005')  ## Schwerwiegende Unfälle mit Sachschäden i.e.S.
q.add_field('VER056')  ## Schwerwiegende Unfälle mit Sachschaden

# get the results as a Pandas DataFrame
df_results = q.results(add_units=True)

# print column names
#for col in df_results.columns:
#    print(col)

# print head of dataframe
#print(df_results.head(10).iloc[:,:7])

# extract relevant columns
df = df_results[['name', 'id', 'year', 'BEV016', 'AI0201', 'AI0113', 'AI1301', 'AI1302', 'AI1303', 'AI1304', 'AI1305', 'VER001', 'VER002', 'VER005', 'VER056']]
```


## Data Cleaning

```{r clean-data}
df_stats <- 
  as_tibble(py$df) %>% 
  ## remove duplicated rows
  unique() %>% 
  ## clean city names
  mutate(
    name = str_remove(name, ", Stadt|, Kreisfreie Stadt|, Landeshauptstadt"),
    name = str_remove(name, ", Stadtkreis")
  ) %>% 
  pivot_longer(
    cols = BEV016:VER056,
    names_to = "stat",
    values_to = "value"
  ) %>% 
  filter(!is.nan(value)) %>% 
  mutate(
    stat_long = case_when(
      stat == 'BEV016' ~ "Einwohner", 
      stat == 'AI0201' ~ "Bevölkerungsdichte (Einwohner je qkm)", 
      stat == 'AI0113' ~ "Siedlungs- und Verkehrsfläche je Einwohner", 
      stat == 'AI1301' ~ "Pkw je 1.000 Einwohner", 
      stat == 'AI1302' ~ "Straßenverkehrsunfälle je 10.000 Einwohner", 
      stat == 'AI1303' ~ "Straßenverkehrsunfälle je 10.000 Kfz", 
      stat == 'AI1304' ~ "Getötete bei Straßenverkehrsunfällen je 100.000 Einwohner", 
      stat == 'AI1305' ~ "Verletzte bei Straßenverkehrsunfällen je 100.000 Einwohner", 
      stat == 'VER001' ~ "Unfälle (insgesamt)", 
      stat == 'VER002' ~ "Unfälle mit Personenschaden", 
      stat == 'VER005' ~ "Schwerwiegende Unfälle mit Sachschäden i.e.S.", 
      stat == 'VER056' ~ "Schwerwiegende Unfälle mit Sachschaden"
    ),
    stat_eng = case_when(
      stat == 'BEV016' ~ "Inhabitants", 
      stat == 'AI0201' ~ "Population density (inhabitants per sq km)", 
      stat == 'AI0113' ~ "Settlement and traffic area per inhabitant", 
      stat == 'AI1301' ~ "Cars per 1,000 inhabitants", 
      stat == 'AI1302' ~ "Road traffic accidents per 10,000 inhabitants", 
      stat == 'AI1303' ~ "Road traffic accidents per 10,000 vehicles", 
      stat == 'AI1304' ~ "Fatalities in road traffic accidents per 100,000 inhabitants", 
      stat == 'AI1305' ~ "Persons injured in road traffic accidents per 100,000 inhabitants", 
      stat == 'VER001' ~ "Accidents (total)", 
      stat == 'VER002' ~ "Accidents with personal injury", 
      stat == 'VER005' ~ "Serious accidents with material damage in the narrow sense", 
      stat == 'VER056' ~ "Serious accidents with material damage"
    )
  )

write_rds(df_stats, path = here::here("data", "datenguidepy_accidents.Rds"))
```

***

<details><summary>Session Info</summary>

```{r sessionInfo, echo = F}
Sys.time()
git2r::repository()
sessionInfo()
```

</details>
