---
title: "#30DayMapChallenge Day 12: Movement - Berlin Cycleways by OpenStreetMaps"
author: "Cedric Scherer"
date: "12th of October 2019"
output:
  html_document:
  theme: paper
highlight: kate
editor_options:
  chunk_output_type: console
---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = F)
```

```{r prep}
library(tidyverse)
library(sf)
theme_set(theme_void())

theme_update(
  panel.background = element_rect(fill = "grey90", 
                                  color = "grey90"),
  plot.background = element_rect(fill = "grey90", 
                                 color = "grey90"),
  plot.margin = margin(140, 160, 50, 160)
)
```

```{r data-prep}
sf_bln_roads <- sf::read_sf(dsn = here::here("data", "berlin-latest-free.shp", "gis_osm_roads_free_1.shp"), 
                              layer = "gis_osm_roads_free_1")

sf_bln_water <- sf::read_sf(dsn = here::here("data", "berlin-latest-free.shp", "gis_osm_water_a_free_1.shp"), 
                            layer = "gis_osm_water_a_free_1")

sf_bln_districts <- sf::read_sf(dsn = here::here("data", "Bezirke__Berlin", "Bezirke__Berlin.shp"), 
                                layer = "Bezirke__Berlin")
```

```{r map, fig.width = 12, fig.height = 10.8}
sf_bln_roads_classified <- 
  sf_bln_roads %>% 
  filter(!fclass %in% c("bridleway", "footway", "path", "pedestrian", "steps")) %>% 
  mutate(class = if_else(fclass == "cycleway", "bike", "car"))
  
sf_bln_roads_classified %>% 
  filter(class == "bike") %>% 
  ggplot() + 
    ## Berlin base map
    geom_sf(data = sf_bln_districts,
            fill = "white",
            color = "white",
            size = 0.7) +
    ## water
    geom_sf(data = sf_bln_water,
            fill = "#ccd7ef",  
            color = "#ccd7ef") +
    ## roads designated for cars
    geom_sf(data = sf_bln_roads_classified %>% filter(class == "car"), 
            color = "#c4c5c5", size = 0.2) +
    ## outline roads designated for bikes
    geom_sf(color = "#0c7052", size = 0.6) + 
    ## roads designated for bikes
    geom_sf(color = "#11a579", size = 0.4) 

ggsave(here::here("plots", "Movement_BerlinByBike_shiny.pdf"), 
       width = 15, height = 11.45, device = cairo_pdf)
```

***

```{r session-info}
sessionInfo()
```

