name: ci

on:
  push:
    branches: 
      - master
jobs:
  github-docker-cache:
    runs-on: ubuntu-latest
    steps:
      -
          name: Prepare
          id: prep
          run: |
            GHCR_IMAGE=ghcr.io/correlaid/xberlin
            if [[ $GITHUB_REF == refs/tags/* ]]; then
              TAG=${GITHUB_REF#refs/tags/}
              VERSION=${TAG%-*}
            else
              VERSION="latest"
            fi
            TAGS="${TAGS}${GHCR_IMAGE}:${VERSION},"
            echo ::set-output name=ghcr_image::${GHCR_IMAGE}
            echo ::set-output name=tags::${TAGS}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.prep.outputs.tags }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
